model:
  NAME: BaseSeg
  encoder_args:
    NAME: PointMetaBaseEncoder
    blocks: [1, 4, 7, 4, 4] #[1, 4, 7, 4, 4] #[1, 3, 5, 3, 3]
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1 
    sa_use_res: False 
    width: 64
    in_channels: 4
    expansion: 1 #4
    radius: 0.3
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
    radius_scaling: 2.5
    fused_agg: True
  decoder_args:
    NAME: PointNextDecoder
  cls_args:
    NAME: SegHead
    num_classes: 19
    in_channels: null
    norm_args:
      norm: 'bn'

batch_size: 4
seed: 2425 #1111 #4333 #2425
